import type { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  { id: 'endless', name: 'Rush Hour Endless', subtitle: 'How far can you go? Three car crashes and you\'re out', length: 999999, speedLimit: 45, maxSpeed: 65, features: ['cone', 'stopSign', 'trafficLight', 'parkedCar', 'traffic', 'star'], obstacleGap: 260, parScore: 2000, shoulderColor: 0x2c3a44, endless: true },
  { id: 'parking-lot', name: 'Parking Lot Practice', subtitle: 'Lesson 1 · Slow and steady around the cones', length: 6000, speedLimit: 25, maxSpeed: 40, features: ['cone', 'checkpoint', 'stopSign', 'star'], obstacleGap: 400, parScore: 650, shoulderColor: 0x4a4a50 },
  { id: 'neighborhood', name: 'Neighborhood Drive', subtitle: 'Lesson 2 · Stop signs and parked cars', length: 8000, speedLimit: 35, maxSpeed: 55, features: ['cone', 'stopSign', 'parkedCar', 'checkpoint', 'star'], obstacleGap: 350, parScore: 900, shoulderColor: 0x3c5a34 },
  { id: 'school-zone', name: 'School Zone', subtitle: 'Lesson 3 · 25 mph, kids about — perfect stops only', length: 8500, speedLimit: 25, maxSpeed: 45, features: ['cone', 'stopSign', 'parkedCar', 'checkpoint', 'star'], obstacleGap: 300, parScore: 1000, shoulderColor: 0x4f6a3d },
  { id: 'downtown', name: 'Downtown Cruise', subtitle: 'Lesson 4 · Traffic lights and tight streets', length: 9000, speedLimit: 35, maxSpeed: 55, features: ['cone', 'trafficLight', 'parkedCar', 'checkpoint', 'star'], obstacleGap: 320, parScore: 1100, shoulderColor: 0x35414a },
  { id: 'rush-hour', name: 'Rush Hour', subtitle: 'Lesson 5 · Live traffic everywhere — keep your cool', length: 9500, speedLimit: 40, maxSpeed: 60, features: ['traffic', 'trafficLight', 'checkpoint', 'cone', 'star'], obstacleGap: 290, parScore: 1200, shoulderColor: 0x35414a },
  { id: 'night-shift', name: 'Night Shift', subtitle: 'Lesson 6 · Low visibility. Trust your training', length: 9500, speedLimit: 40, maxSpeed: 60, features: ['cone', 'stopSign', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 300, parScore: 1250, shoulderColor: 0x141420, nightAlpha: 0.32 },
  { id: 'highway-run', name: 'Highway Run', subtitle: 'Lesson 7 · Higher speeds, higher stakes', length: 11000, speedLimit: 55, maxSpeed: 70, features: ['traffic', 'cone', 'checkpoint', 'star'], obstacleGap: 340, parScore: 1300, shoulderColor: 0x4a4a50 },
  { id: 'construction', name: 'Construction Zone', subtitle: 'Lesson 8 · Cones for days. Thread the needle', length: 10000, speedLimit: 30, maxSpeed: 50, features: ['cone', 'parkedCar', 'stopSign', 'checkpoint', 'star'], obstacleGap: 220, parScore: 1350, shoulderColor: 0x5a4a32 },
  { id: 'city-gauntlet', name: 'City Gauntlet', subtitle: 'Lesson 9 · Everything at once, dense and fast', length: 11500, speedLimit: 45, maxSpeed: 65, features: ['cone', 'stopSign', 'trafficLight', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 250, parScore: 1500, shoulderColor: 0x35414a },
  { id: 'road-test-final', name: 'Road Test Final', subtitle: 'Final Exam · The full 5-star DrivingKlass road test', length: 13000, speedLimit: 45, maxSpeed: 65, features: ['cone', 'stopSign', 'trafficLight', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 240, parScore: 1700, shoulderColor: 0x2c3a44, nightAlpha: 0.18 },

  // ---- Additional lessons (v2) — additive only, existing levels above are untouched ----
  { id: 'roundabout-rookie', name: 'Roundabout Rookie', subtitle: 'Lesson 11 · Yield on entry, single-lane circle', length: 9000, speedLimit: 25, maxSpeed: 45, features: ['cone', 'stopSign', 'checkpoint', 'star', 'traffic'], obstacleGap: 300, parScore: 1050, shoulderColor: 0x3c5a34, pedDensityMul: 0.6, isNew: true },
  { id: 'quick-turns-gauntlet', name: 'Quick Turns Gauntlet', subtitle: 'Lesson 12 · Snappy lane changes and cone chicanes', length: 9500, speedLimit: 35, maxSpeed: 55, features: ['cone', 'traffic', 'checkpoint', 'star', 'parkedCar'], obstacleGap: 210, parScore: 1200, shoulderColor: 0x3a3a44, isNew: true },
  { id: 'rainy-slick-streets', name: 'Rainy Slick Streets', subtitle: 'Lesson 13 · Wet pavement, longer stops, patience', length: 10000, speedLimit: 30, maxSpeed: 50, features: ['cone', 'stopSign', 'trafficLight', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 300, parScore: 1250, shoulderColor: 0x2a3540, weatherTint: { color: 0x2a5878, alpha: 0.22 }, isNew: true },
  { id: 'bus-stop-blockers', name: 'Bus Stop Blockers', subtitle: 'Lesson 14 · Buses and delivery vans on tight streets', length: 10000, speedLimit: 35, maxSpeed: 55, features: ['parkedCar', 'traffic', 'stopSign', 'checkpoint', 'star', 'cone'], obstacleGap: 250, parScore: 1250, shoulderColor: 0x35414a, pedDensityMul: 1.3, isNew: true },
  { id: 'door-zone-alley', name: 'Door Zone Alley', subtitle: 'Lesson 15 · Parked cars everywhere — leave a lane', length: 9500, speedLimit: 30, maxSpeed: 50, features: ['parkedCar', 'parkedCar', 'cone', 'checkpoint', 'star'], obstacleGap: 200, parScore: 1250, shoulderColor: 0x40444a, isNew: true },
  { id: 'emergency-make-way', name: 'Emergency Make-Way', subtitle: 'Lesson 16 · Yield and hold your lane discipline', length: 10500, speedLimit: 40, maxSpeed: 60, features: ['traffic', 'trafficLight', 'checkpoint', 'star', 'cone'], obstacleGap: 260, parScore: 1350, shoulderColor: 0x35414a, isNew: true },
  { id: 'multi-stop-delivery', name: 'Multi-Stop Delivery', subtitle: 'Lesson 17 · Every checkpoint counts — no skipped stops', length: 11000, speedLimit: 35, maxSpeed: 55, features: ['stopSign', 'checkpoint', 'parkedCar', 'traffic', 'cone', 'star'], obstacleGap: 260, parScore: 1400, shoulderColor: 0x3c5a34, isNew: true },
  { id: 'foggy-backroads', name: 'Foggy Backroads', subtitle: 'Lesson 18 · Low visibility. Slow, smooth, steady', length: 10500, speedLimit: 35, maxSpeed: 55, features: ['cone', 'stopSign', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 280, parScore: 1350, shoulderColor: 0x37403a, nightAlpha: 0.25, weatherTint: { color: 0xa0a8b0, alpha: 0.18 }, isNew: true },
  { id: 'snowbelt-skid', name: 'Snowbelt Skid', subtitle: 'Lesson 19 · Icy roads — feather the throttle', length: 10500, speedLimit: 30, maxSpeed: 50, features: ['cone', 'stopSign', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 280, parScore: 1400, shoulderColor: 0x7a8890, weatherTint: { color: 0xdfe8f0, alpha: 0.22 }, isNew: true },
  { id: 'pedestrian-plaza', name: 'Pedestrian Plaza', subtitle: 'Lesson 20 · Crowded crossings, kids and dogs about', length: 10000, speedLimit: 25, maxSpeed: 45, features: ['cone', 'stopSign', 'parkedCar', 'checkpoint', 'star'], obstacleGap: 260, parScore: 1450, shoulderColor: 0x4f6a3d, pedDensityMul: 2.2, dogDensityMul: 1.6, isNew: true },
  { id: 'two-lane-roundabout', name: 'Two-Lane Roundabout', subtitle: 'Lesson 21 · Pick your lane, exit correctly', length: 11000, speedLimit: 30, maxSpeed: 50, features: ['cone', 'traffic', 'stopSign', 'checkpoint', 'star', 'parkedCar'], obstacleGap: 240, parScore: 1500, shoulderColor: 0x3c4a5a, isNew: true },
  { id: 'late-night-diner', name: 'Late Night Diner Run', subtitle: 'Lesson 22 · Neon streets, tipsy pedestrians, stay alert', length: 11500, speedLimit: 35, maxSpeed: 55, features: ['cone', 'stopSign', 'trafficLight', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 250, parScore: 1550, shoulderColor: 0x1e2030, nightAlpha: 0.34, pedDensityMul: 1.4, isNew: true },
  { id: 'precision-parking-final', name: 'Precision Parking Final', subtitle: 'Lesson 23 · Cone slaloms, checkpoint precision', length: 10500, speedLimit: 25, maxSpeed: 40, features: ['cone', 'cone', 'checkpoint', 'star', 'parkedCar'], obstacleGap: 180, parScore: 1500, shoulderColor: 0x4a4a50, isNew: true },
  { id: 'everything-at-once', name: 'Everything At Once Mastery', subtitle: 'Lesson 24 · The ultimate combined stage — five-star drivers only', length: 14000, speedLimit: 40, maxSpeed: 65, features: ['cone', 'stopSign', 'trafficLight', 'parkedCar', 'traffic', 'checkpoint', 'star'], obstacleGap: 220, parScore: 1900, shoulderColor: 0x2c3a44, nightAlpha: 0.20, weatherTint: { color: 0x3a5878, alpha: 0.14 }, pedDensityMul: 1.6, dogDensityMul: 1.4, isNew: true }
];

export function getLevel(id: string): LevelConfig {
  return LEVELS.find((l) => l.id === id) ?? LEVELS[1];
}
