// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Driving Klass user's profile: id, email, name, and role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roleRow }] = await Promise.all([
      supabase.from("profiles").select("id, full_name, email").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle()
    ]);
    const result = {
      user_id: userId,
      email: ctx.getUserEmail() ?? profile?.email ?? null,
      full_name: profile?.full_name ?? null,
      role: roleRow?.role ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-my-sessions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { z } from "npm:zod@^3.25.76";
var list_my_sessions_default = defineTool2({
  name: "list_my_sessions",
  title: "List my sessions",
  description: "List driving/testing sessions for the signed-in user (student, instructor, or admin). RLS scopes visibility.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max sessions to return."),
    status: z.enum(["scheduled", "completed", "cancelled", "any"]).default("any").describe("Filter by session status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let q = supabase.from("sessions").select("id, scheduled_at, duration_minutes, status, session_type, pickup_address, dropoff_address, student_id, instructor_id").order("scheduled_at", { ascending: false }).limit(limit);
    if (status !== "any") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-report-cards.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_report_cards_default = defineTool3({
  name: "list_my_report_cards",
  title: "List my report cards",
  description: "List report cards visible to the signed-in user. RLS scopes visibility (students see their own; instructors/admins see theirs).",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("report_cards").select("id, student_id, instructor_id, session_id, status, created_at, updated_at, is_public, public_share_slug").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { report_cards: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wfuadudqtcmpdbgtgazh";
var mcp_default = defineMcp({
  name: "driving-klass-mcp",
  title: "Driving Klass MCP",
  version: "0.1.0",
  instructions: "Tools for Driving Klass. Use `whoami` to check the signed-in user, `list_my_sessions` for their driving/testing sessions, and `list_my_report_cards` for their report cards. All results are scoped by RLS to the caller.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_sessions_default, list_my_report_cards_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
